steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nestjs-graphql-test-backend:$COMMIT_SHA', '.']
    dir: "backend"
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nestjs-graphql-test-backend:$COMMIT_SHA']
    dir: "backend"
  - name: "gcr.io/google-appengine/exec-wrapper"
    entrypoint: "bash"
    args:
      - "-c"
      - "/buildstep/execute.sh -i $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA -e DATABASE_URL=$$DATABASE_URL -s $_CLOUDSQL_INSTANCE_FULL_NAME -- yarn prisma migrate deploy"
    secretEnv: ["DATABASE_URL"]
    dir: "backend"
images:
  - 'gcr.io/$PROJECT_ID/nestjs-graphql-test-backend:$COMMIT_SHA'
timeout: 2000s
substitutions:
  _DEPLOY_REGION: by-terraform
  _CLOUDSQL_INSTANCE_FULL_NAME: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform
  _SERVICE_ACCOUNT: by-terraform
  # _CONTENTS_BUCKET_NAME: by-terraform
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/NESTJS_GRAPHQL_TEST_DATABASE_URL/versions/latest
      env: DATABASE_URL

# ビルド結果に生成したイメージ情報を表示する
# https://cloud.google.com/build/docs/building/build-containers
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA'
